# Numpy

In [1]:
import numpy as np
n1=np.array([10,20,30])
n1

array([10, 20, 30])

In [2]:
n2=np.array([[10,20,30],[40,50,60]])
n2

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
n2.shape

(2, 3)

In [4]:
n2.shape=(3,2)
n2.shape

(3, 2)

In [5]:
n3=np.ones([5,5])
n4=np.ones([5,5])
n3+n4+n3*n4*n3*n4

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [6]:
n5=np.full([5,5],10)
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [7]:
n6=np.arange(0,20+1,2)
print(n6)
str(n6)

[ 0  2  4  6  8 10 12 14 16 18 20]


'[ 0  2  4  6  8 10 12 14 16 18 20]'

In [8]:
n7=np.random.randint(1,141,10)
n7

array([ 79, 104,  64, 121, 119,  75,  47,  52,  53, 131])

# Joining the numpy arrays:
## vstack(), hstack(), column_stack()

In [2]:
import numpy as  np
n1=[10,20,30]
n2=[40,50,60]

In [3]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [5]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# Numpy array mathemetics:

In [7]:
n3=[10,20,30,40,50,60]
n4=[50,60,60,80,]

In [8]:
np.intersect1d(n3,n4)

array([50, 60])

In [9]:
np.setdiff1d(n3,n4)

array([10, 20, 30, 40])

In [10]:
np.setdiff1d(n4,n3)

array([80, 90])

In [11]:
np.sum([n1,n2])

210

In [12]:
np.sum([n1,n2],axis=0)

array([50, 70, 90])

In [13]:
np.sum([n1,n2],axis=1)

array([ 60, 150])

# Save and load the array

In [14]:
import numpy as np
n1=np.array([1,2,3,4,5])
np.save('my_arr',n1)

In [15]:
n2=np.load('my_arr.npy')
n2

array([1, 2, 3, 4, 5])

# Numpy Broadcasting

In [16]:
n1+n2

array([ 2,  4,  6,  8, 10])

In [18]:
n3=np.array([[10,20,30],[40,50,60],[70,80,90]])
n4=np.array([5,10,15])
n5=n3+n4
n5

array([[ 15,  30,  45],
       [ 45,  60,  75],
       [ 75,  90, 105]])

In [19]:
n5.transpose()

array([[ 15,  45,  75],
       [ 30,  60,  90],
       [ 45,  75, 105]])

In [20]:
print(n3[0],"\n")
print(n3[1])

[10 20 30] 

[40 50 60]


In [21]:
print(n3[:,1],"\n")
print(n3[:,2])

[20 50 80] 

[30 60 90]


In [22]:
print(n3[0,1],"\n")
print(n3[1,1],"\n")
print(n3[2,1])

20 

50 

80
